language: node_js
node_js:
- 5.6
before_script:
- gem install percy-cli
after_success:
- '[ "$TRAVIS_SECURE_ENV_VARS" = "true" ] && npm run perceptual-diff'
sudo: false
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: cdOHRe6Mq7341swW/VE2XZjos08WACv7rq/Cudh2ddKd9m5whC5MPz+cGKR6nuWOBk/az93kIhC4QNgBx7epiG3+1Nggs7g26O+JMAleEP9S1bTSJV+AM9HvPHiA0VtQQPntw9toTAvFdtXkx/6nmg9Amrz9ISyVabFp9s+sL00=
  on:
    tags: true
    all_branches: true
env:
  global:
    secure: yirvYUS/RoOpQyKtSa4bpWT/5Vi06sJScpbNlG7XlhRYp7fnUG/xM4Jt45kAh/hci8MjWlmZGWaklLnDo/C3B670UKSGldGpe71uGyZboLozK9T/WH2At6aHJWA0PDEOTrqtTxgTgP0yj/r8Hy1dJDWfs1FFXLVL8YpH2YBLtrU=
